# Generated by Django 5.0.3 on 2024-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("deadline", models.DateField(auto_now=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(related_name="tasks", to="list.tags")),
            ],
            options={
                "ordering": ["status", "-date"],
            },
        ),
    ]
